module.exports = {
  taipeiCity: 'taipei-city',
  newTaipeiCity: 'new-taipei-city',
  taoyuanCity: 'taoyuan-city',
  taichungCity: 'taichung-city',
  tainanCity: 'tainan-city',
  kaohsiungCity: 'kaohsiung-city',
  keelungCity: 'keelung-city',
  hsinchuCity: 'hsinchu-city',
  chiayiCity: 'chiayi-city',
  hsinchuCounty: 'hsinchu-county',
  miaoliCounty: 'miaoli-county',
  changhuaCounty: 'changhua-county',
  nantouCounty: 'nantou-county',
  yunlinCounty: 'yunlin-county',
  chiayiCounty: 'chiayi-county',
  pingtungCounty: 'pingtung-county',
  yilanCounty: 'yilan-county',
  hualienCounty: 'hualien-county',
  taitungCounty: 'taitung-county',
  penghuCounty: 'penghu-county',
  kinmenCounty: 'kinmen-county',
  lienchiangCounty: 'lienchiang-county',
  all() {
    return [
      this.taipeiCity,
      this.newTaipeiCity,
      this.taoyuanCity,
      this.taichungCity,
      this.tainanCity,
      this.kaohsiungCity,
      this.keelungCity,
      this.hsinchuCity,
      this.chiayiCity,
      this.hsinchuCounty,
      this.miaoliCounty,
      this.changhuaCounty,
      this.nantouCounty,
      this.yunlinCounty,
      this.chiayiCounty,
      this.pingtungCounty,
      this.yilanCounty,
      this.hualienCounty,
      this.taitungCounty,
      this.penghuCounty,
      this.kinmenCounty,
      this.lienchiangCounty,
    ];
  },
};
