version: '3'

services:
  redis:
    image: redis:5
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ../ct-volumes/redis_data:/data
    restart: always
    networks:
      - backend
  mongo:
    image: mongo
    restart: always
 #   environment:
 #     MONGO_INITDB_ROOT_USERNAME: root
 #     MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ../ct-volumes/mongo_data:/data/db
      - ../ct-volumes/bucket:/bucket
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - backend
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#    networks:
#      - backend
#  mongo:
#    image: mongo:latest
#    restart: always
#    expose:
#      - 27017
#    ports:
#      - "27017:27017"
#    volumes:
#      - ../ct-volumes/mongo_data:/data/db
#      - ../ct-volumes/bucket:/bucket
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#    networks:
#      - backend
  server:
    build:
      context: .
      dockerfile: scripts/api/development/Dockerfile
    container_name: ct-api-local-container
    image: ct-api-local-image
    restart: always
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - /camera-trap-api/node_modules
      - .:/camera-trap-api
      - ../ct-volumes/tmp:/tmp
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo
    networks:
      - backend
networks:
  backend:

