version: '3'
services:
  redis:
    image: redis:5
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ~/redis_data:/data
    restart: always
    networks:
      - backend
  mongo:
    image: mongo:latest
    restart: always
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - ~/mongo_data:/data/db
    networks:
      - backend
  server:
    build:
      context: .
      dockerfile: scripts/api/development/Dockerfile
    restart: always
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
      - 3000:3000
    links:
      - redis
      - mongo
    networks:
      - backend

networks:
  backend:
    driver: bridge

