version: '3'

services:
  redis:
    image: redis:5
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ../ct-volumes/redis_data:/data
    restart: always
    networks:
      - backend
  mongo:
    image: mongo:latest
    restart: always
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - ../ct-volumes/mongo_data:/data/db
      - ../ct-volumes/bucket:/bucket
    networks:
      - backend
  server:
    build:
      context: .
      dockerfile: scripts/api/production/Dockerfile
    container_name: ct-api-production-container
    image: ct-api-production-image
    restart: always
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - /camera-trap-api/node_modules
      - .:/camera-trap-api
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo
    networks:
      - backend

networks:
  backend:

