###
POST {{host}}/project/location-month-identified-num
Content-Type: application/json

{
  "year": 2017,
  "projectId": "d8064aa7-9643-44fb-bed9-1f23a690f968"
}

###
POST {{host}}/project/related-to-me
Content-Type: application/json
camera-trap-user-id: {{userId}}

###
POST {{host}}/project/add-user-to-project
Content-Type: application/json

{
  "userId": "{{userId}}"
}
