###
POST {{host}}/project/location-month-identified-num
Content-Type: application/json

{
  "year": 2017,
  "projectTitle": "測試計畫1"
}

###
POST {{host}}/project/related-to-me
Content-Type: application/json
camera-trap-user-id: {{userId}}

###
POST {{host}}/project/add-user-to-project
Content-Type: application/json

{
  "userId": "{{userId}}"
}
