version: 2.1

orbs:
  gcloud: circleci/gcp-cli@1.0.1
  docker: circleci/docker-publish@0.1.0

  node10:
    orbs:
      aws: circleci/aws-cli@0.1.4

    commands:
      checkout_install:
        description: Cehckout sources and install node_modules
        steps:
          - checkout
          - restore_cache:
              key: node_modules#{{ checksum "package-lock.json" }}
          - run: npm i
          - save_cache:
              key: node_modules#{{ checksum "package-lock.json" }}
              paths:
                - node_modules
          - run: git checkout -- .
          - run:
              name: Decrypt API Secret
              command: |
                sudo apt-get -y -qq update
                sudo apt-get install bsdmainutils
                yarn --silent transcrypt -p "$API_SECRET" -y
                yarn build-env

    executors:
      default:
        environment:
          - TZ: Asia/Taipei
        docker:
          - image: circleci/node:10
    jobs:
      aws-deploy:
        executor: default
        steps:
          - checkout_install
          - run:
              name: Install AWS CLI
              command: |
                sudo apt-get -y -qq update
                sudo apt-get install python-pip python-dev build-essential
                sudo pip install awsebcli --upgrade
          # Deploy to the Elastic Beanstalk corresponding to the current branch
          - run:
              name: Deploy on AWS EB
              command: |
                source .env
                npx ts-node scripts/aws-deploy-start
                eb deploy --label $CIRCLE_SHA1
          - run: npx ts-node scripts/aws-deploy-done

      run:
        parameters:
          command:
            type: string
            default: npm test
          section:
            type: string
            default: <<parameters.command>>
        executor: default
        steps:
          - checkout_install
          - run:
              name: <<parameters.section>>
              command: <<parameters.command>>

workflows:
  version: 2
  Test & Lint & Deploy:
    jobs:
      - node10/aws-deploy:
          filters:
            branches:
              only: /^(prod|dev|ci)$/
          requires:
            - lint
            - test
      - node10/run:
          name: lint
          section: Run ESLint with only modified *.js
          command: npx eslint $(git diff origin/master..HEAD --name-only -- '*.js')
      - node10/run:
          name: test
          command: npm test
