version: 2.1

vars:
  setup_docker: &setup_docker
    setup_remote_docker:
      docker_layer_caching: true

  branch_is_deploy: &branch_is_deploy
    filters:
      branches:
        only: master

orbs:
  node:
    orbs:
      aws-ecr: circleci/aws-ecr@4.0.1
      aws-cli: circleci/aws-cli@0.1.13
      aws-ecs: circleci/aws-ecs@0.0.11
    executors:
      aws:
        environment:
          - TZ: Asia/Taipei
          - NVM_DIR: /opt/circleci/.nvm
        machine:
          docker_layer_caching: true
      default:
        environment:
          - TZ: Asia/Taipei
        docker:
          - image: circleci/node:10
    commands:
      set-env:
        description: Set Up Env
        steps:
          - run:
              name: Set ENV
              command: |
                if [ $CIRCLE_BRANCH = "prod" ];then
                  echo "export ENV='production'" >> $BASH_ENV
                else
                  echo "export ENV='staging'" >> $BASH_ENV
                fi
                source $BASH_ENV
      use-node:
        description: Install Node
        parameters:
          v:
            type: string
            default: 10.15.3
        steps:
          - run:
              name: Use Node v<< parameters.v >>
              command: |
                TAR=~/node.tar.xz
                NODE_PATH=~/node
                curl https://nodejs.org/dist/v<< parameters.v >>/node-v<< parameters.v >>-linux-x64.tar.xz -o $TAR
                mkdir $NODE_PATH && tar xf $TAR -C $NODE_PATH --strip-components 1

                echo "export PATH=$NODE_PATH/bin:\$PATH" >> $BASH_ENV
                source $BASH_ENV

      docker-build-push:
        description: Docker build
        parameters:
          repo:
            type: string
            default: repo-name
          url:
            type: string
            default: dkr.ecr.ap-northeast-1.amazonaws.com
          tag:
            type: string
            default: $CIRCLE_SHA1
        steps:
          - *setup_docker
          - add_ssh_keys:
              fingerprints:
                - "07:38:69:80:a9:81:54:19:7d:bf:cb:73:7a:34:64:24"
                - "2c:52:a7:73:52:6f:e3:d4:9f:f0:7c:96:c1:4b:4a:d1"
          - run:
              name: Build Docker Image
              command: |
                IMAGE=<< parameters.url >>/<< parameters.repo >>:<< parameters.tag >>
                echo "$ID_RSA"
                docker build --no-cache . -t $IMAGE --build-arg SSH_KEY="$ID_RSA"
                docker images $IMAGE
                docker push $IMAGE
      checkout-install:
        description: Checkout sources and install node_modules
        steps:
          - checkout
          - restore_cache:
              key: node_modules#{{ checksum "package-lock.json" }}
          - run: npm i
          - save_cache:
              key: node_modules#{{ checksum "package-lock.json" }}
              paths:
                - node_modules
          - run:
              name: Set Env
              command: |
                echo "$(node scripts/export-env)" >> $BASH_ENV
                source $BASH_ENV
    jobs:
      build_api:
        executor: aws
        steps:
          - add_ssh_keys:
              fingerprints:
                - "07:38:69:80:a9:81:54:19:7d:bf:cb:73:7a:34:64:24"
                - "2c:52:a7:73:52:6f:e3:d4:9f:f0:7c:96:c1:4b:4a:d1"
          - use-node
          - run: node -v
          - checkout-install
          - aws-ecr/build-and-push-image:
              repo: ct-api-$ENV
              tag: $CIRCLE_SHA1
              dockerfile: 'scripts/api/$ENV/Dockerfile'
      build_task:
        executor: aws
        steps:
          - add_ssh_keys:
              fingerprints:
                - "07:38:69:80:a9:81:54:19:7d:bf:cb:73:7a:34:64:24"
                - "2c:52:a7:73:52:6f:e3:d4:9f:f0:7c:96:c1:4b:4a:d1"
          - use-node
          - run: node -v
          - checkout-install
          - aws-ecr/build-and-push-image:
              repo: ct-task-$ENV
              tag: $CIRCLE_SHA1
              dockerfile: 'scripts/task-worker/$ENV/Dockerfile'
      deploy_api:
        executor: aws
        steps:
          - set-env
          - aws-cli/install
          - aws-cli/configure:
              aws-access-key-id: AWS_ACCESS_KEY_ID
              aws-region: AWS_REGION
          - aws-ecs/update-service:
              family: ct-api-$ENV-service
              cluster-name: camera-trap-$ENV-cluster
              container-image-name-updates: 'container=ct-api-$ENV-service,image-and-tag=$AWS_ECR_ACCOUNT_URL/ct-api-$ENV:$CIRCLE_SHA1'
      deploy_task:
        executor: aws
        steps:
          - set-env
          - aws-cli/install
          - aws-cli/configure:
              aws-access-key-id: AWS_ACCESS_KEY_ID
              aws-region: AWS_REGION
          - aws-ecs/update-service:
              family: ct-task-$ENV-service
              cluster-name: camera-trap-$ENV-cluster
              container-image-name-updates: 'container=ct-task-$ENV-service,image-and-tag=$AWS_ECR_ACCOUNT_URL/ct-task-$ENV:$CIRCLE_SHA1'

      lint:
        executor: default
        steps:
          - checkout-install
          - run: npm run lint

workflows:
  version: 2
  Test & Lint & Build:
    jobs:
      - node/lint
      - node/build_api:
          filters:
            branches:
              only: 
                - prod
                - dev
                - circle-ssh
          requires:
            - node/lint
      - node/build_task:
          filters:
            branches:
              only: 
                - prod
                - dev
                - circle-ssh
          requires:
            - node/lint
      - node/deploy_api:
          filters:
            branches:
              only:
                - prod
                - dev
                - circle-ssh
          requires:
            - node/lint
            - node/build_api
      - node/deploy_task:
          filters:
            branches:
              only:
                - prod
                - dev
                - circle-ssh
          requires:
            - node/lint
            - node/build_task
