version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - node10
jobs:
  node10:
    working_directory: ~/camera-trap-api
    docker:
      - image: node:10.15.0
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run lint
          name: lint
          command: npm run lint

