version: 2.1

vars:
  setup_docker: &setup_docker
    setup_remote_docker:
      docker_layer_caching: true

  branch_is_deploy: &branch_is_deploy
    filters:
      branches:
        only: master

orbs:
  node:
    orbs:
      aws-ecr: circleci/aws-ecr@4.0.1
    executors:
      default:
        environment:
          - TZ: Asia/Taipei
        docker:
          - image: circleci/node:10
    commands:
      checkout_install:
        description: Checkout sources and install node_modules
        steps:
          - checkout
          - restore_cache:
              key: node_modules#{{ checksum "package-lock.json" }}
          - run: npm i
          - save_cache:
              key: node_modules#{{ checksum "package-lock.json" }}
              paths:
                - node_modules
          - run:
              name: Set Env
              command: |
                echo "$(node scripts/export-env)" >> $BASH_ENV
                source $BASH_ENV
    jobs:
      build:
        executor: default
          steps:
            - checkout_install
            - aws-ecr/build_and_push_image:
                tag: $CIRCLE_SHA1


      lint:
        executor: default
        steps:
          - checkout_install
          - run: npm run lint

workflows:
  version: 2
  Test & Lint & Build:
    jobs:
      - node/lint
      - node/build

jobs:
  node10:
    working_directory: ~/camera-trap-api
    docker:
      - image: node:10.15.0
      - image: circleci/mongo:4.1.9
      - image: circleci/redis:5.0.4
    environment:
      - MONGO_URL: "mongodb://localhost:27017/cameraTrap_test"
      - REDIS_URL: "redis://localhost:6379/2"
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run lint
          name: lint
          command: npm run lint
      - run: # run db init
          name: DatabaseInit
          command: npm run db:init
      - run: # run test
          name: test
          command: npm run test
